### ISSUE TITLE
is it possible config confirmation on command basis ?

### ISSUE THREAD

**Issue by oliveagle** [tokozedg/sman#9]
some command don't need any arguments.  I just want to exec it with out confirmation.  but most of time, I need confirmation globally.

so is it possible to config confirmation on command level. e.g.:

```yaml
xrandr:ls:
  do: exec
  desc: xrandr list monitors with highlight
  confiram: false
  command: xrandr | ack -o '.*connected( primary)?' | awk '{print $1,$2,$3}' | ack --passthru --color '\bconnected' | ack --passthru --color --color-match red 'primary'
```
